Minimum generation for Generators
PyPSA/PyPSA pull request #1047
Opened 2024-09-25 17:40 UTC by cpschau

## Changes proposed in this Pull Request
This PR introduces a new optional field for generators, namely `p_sum`. This field restricts the overall amount of energy generated by the unit during a single optimization horizon within the constraint `define_generators_constraints`.

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [ ] I consent to the release of this PR's code under the MIT license.

2024-09-27 12:39 UTC, lkstrp approved these changes
Some small stuff and I check for another test with snapshots

2024-09-27 12:39 UTC, lkstrp commented on doc/references/release-notes.rst
> +  and can be used as aliases without any deprecation warning for now.
```suggestion
```

2024-09-27 12:39 UTC, lkstrp commented on pypsa/consistency.py
> +    component (Component): The generator component to be checked.
```suggestion
    component : Component
        The generator component to be checked.
```

2024-09-27 12:39 UTC, lkstrp commented on pypsa/consistency.py
> +    This will check the specified generator component in the network for the described inconsistencies.
```suggestion
```

2024-09-27 12:39 UTC, lkstrp commented on pypsa/optimization/constraints.py
> +    This will add the energy sum constraints to the generators in the network model.
```suggestion
    Defines energy sum constraints for generators in the network model.

    This function adds constraints to the network model to ensure that the total
    energy generated by each generator over the specified snapshots meets the
    minimum and maximum energy sum requirements.
    
    Added constraints:
    - Minimum Energy Sum (e_sum_min): Ensures that the total energy generated by
      each generator over the specified snapshots is at least the minimum energy
      sum specified.
    - Maximum Energy Sum (e_sum_max): Ensures that the total energy generated by
      each generator over the specified snapshots does not exceed the maximum
      energy sum specified.

    Parameters
    ----------
    n (Network): The network object containing the model and generator data.
    sns (list): A list of snapshots (time steps) over which the constraints are applied.

    Returns
    -------
    None

```

2024-09-27 12:39 UTC, lkstrp commented on pypsa/optimization/constraints.py
> +    e_sum_min = n.df(c).loc[e_sum_min_set, "e_sum_min"]
```suggestion
    e_sum_min = n.static(c).loc[e_sum_min_set, "e_sum_min"]
```

2024-09-27 12:39 UTC, lkstrp commented on pypsa/optimization/constraints.py
> +    e_sum_max = n.df(c).loc[e_sum_max_set, "e_sum_max"]
```suggestion
    e_sum_max = n.static(c).loc[e_sum_max_set, "e_sum_max"]
```

2024-09-27 12:39 UTC, lkstrp commented on test/test_consistency_check.py
> +def test_unconsistent_e_sum_values(consistent_n, caplog):
```suggestion
def test_inconsistent_e_sum_values(consistent_n, caplog):
```

2024-09-27 14:04 UTC, lkstrp requested changes
needs double check with test

2024-10-01 11:48 UTC, fneum approved these changes
Great!

2024-10-01 11:48 UTC, fneum commented on pypsa/optimization/constraints.py
> +    m.add_constraints(lhs, ">=", rhs, name=f"{c}-e_sum_min")
```suggestion
    m.add_constraints(e, ">=", e_sum_min, name=f"{c}-e_sum_min")
```
I think this would be ok. But not necessary to change now.

2024-10-01 13:08 UTC, merged

2024-10-09 09:59 UTC, PriyeshGosai commented
Is it possible to include this function to links?

2024-10-14 10:08 UTC, lkstrp commented
At least not planned in a similar approach. What is your use case for this?
A link is not a source, but must be linked to generators/stores and therefore does not justify the component extension with another attribute enough. Also, the implementation here is too specific for it to be extended nicely for other components at the moment.

2024-10-14 13:06 UTC, FabianHofmann commented
I think generalizing it would be helpful. Often total transmission of individual links or total energy consumed/produced by conversion technologies such as electrolyzers need to be fixed per optimization horizon. The only question is whether the constraint should run on p0 or p1, where I would strongly lean towards p0. 

A side note: I don't like the current naming of the constraint as it is very unspecific. When generalizing, i would prefer something like "define_total_production_constraint"

2025-01-03 09:49 UTC, PriyeshGosai commented
@lkstrp I see that @FabianHofmann addressed the need for the generalization of this constraint. I agree with the use cases. I also agree we should set the constraint at p0.

2025-02-16 14:27 UTC, SunnyBlueWhite commented
e_sum_max is a fixed value, how should I make it vary with the installed capacity?