test: add doctests
PyPSA/PyPSA pull request #1114
Opened 2024-12-19 08:36 UTC by lkstrp

Ref #1105 

## Changes proposed in this Pull Request
- Adds doctests to testing to to test any Example code in docstrings
- Changes naming convention from Component Type (Generator, Store) etc. to Component Variant

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] I consent to the release of this PR's code under the MIT license.

2025-01-06 11:20 UTC, fneum requested changes
Looks great, but I am unsure about the name "Component Variant". I find "component type" or "component class" or simply "component(s)" more intuitive. What do you think?

2025-01-06 11:20 UTC, fneum commented on doc/user-guide/design.rst
> +For each component variant (line, transformer, generator, etc.), which must be
I see where this comes from (as `class` and `type` are Python jargon), but do you think it's feasible/sensible to name it "component type" or "component class"?

2025-01-06 11:20 UTC, fneum commented on pypsa/networks.py
> +        That is because timesteps and periods are not necessarily unique or entire
```suggestion
        That is because timesteps and periods are not necessarily unique or complete
```
This?

2025-01-06 11:20 UTC, fneum commented on pypsa/plot.py
> +    >>> autogenerate_coordinates(n) # doctest: +SKIP
not sure if this function is deterministic

2025-01-06 13:22 UTC, lkstrp commented
The thing is, we have a couple of "components":
- `ComponentVariant`: Default values and attributes for each component, `e.g.` generator variant or carrier variant. Basically just the information from `components.csv` and represents data for a single component.
- `Components` class: Stores concrete information for a number of component instances: e.g. `line_1`, `line_2`, similar to the df in n.generators. It references the corresponding `Variant` but does not inherit from it.
  - This also includes subclasses like `Generators`, `GenericComponents` for variant-specific logic.

So "component" and "component class" should better refer to the second one, which is also the one mostly used. I wouldn't start by only distinguishing between a single "component" and multiple "components". That already lead to confusion with the current named tuple implementation. And the "component" namespace is also already taken for backwards compatibility.

I do not like "type" because the `ComponentVariant` also had a `type` attribute (from `components.csv`: `controllable_one_port`, `passive_one_port` etc.). This has been renamed to `category`, but is still accessible via `type`. Then you would have a `Components` class of type `Generators` with type `controllable_one_port`?
Also, not only do you have the Python jargon problem, but Python type and the type/variant attribute would refer to completely different things:
``` python
type(c) # -> "Generators" class
c.type # -> ComponentType instance
c.type.list_name # -> "generators"
c.type.category # -> "controllable_one_port"
c.type.type # -> "controllable_one_port" # Deprecated
```
vs
``` python
type(c) # -> "Generators" class
c.variant # -> ComponentType instance
c.variant.list_name # -> "generators"
c.variant.category # -> "controllable_one_port"
c.variant.type # -> "controllable_one_port" # Deprecated
```

But I agree that "variant" might not be a very intuitive name.

So three options:
1. Rename to "variant"
2. Stick with "type" and rename the access to something like `c.component_type` or `c.ctype`.
3. Come up with something completely different?

Maybe I like the second option most, but there might be another better name as well. Let me know what you think. Also pinging the PyPSA trinity here @FabianHofmann @coroa

2025-01-06 13:23 UTC, lkstrp commented on pypsa/plot.py
> +    >>> autogenerate_coordinates(n) # doctest: +SKIP
It is not, you need to add `# doctest: +SKIP` for these cases from now on

2025-01-06 13:37 UTC, fneum commented
Yes, let's hear other opinions. I would tend to go for option 2.

2025-01-06 15:23 UTC, FabianHofmann commented
mmh, I actually don't know, no strong opinion here. If I understand correctly that is about the common structure of component classes I find ComponentVariant nice

2025-01-07 10:39 UTC, lkstrp commented
Let's go with option 2!
No need to change the common notation so far, and we just fix the ambiguity with `c.component_type` and `c.ctype`.

2025-01-07 12:26 UTC, merged