minimuse use of six module
PyPSA/PyPSA pull request #196
Opened 2020-07-19 20:38 UTC by fneum

Closes #163 .

## Changes proposed in this Pull Request

`six` is the Python 3 and Python 2 compatibility library https://six.readthedocs.io/. Since we dropped Python 2 support, we should phase out the use of this module.

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

2020-09-25 11:25 UTC, fneum commented
I would like to take the current status as a first step, then finalise in another PR.

2020-11-03 23:30 UTC, coroa requested changes

2020-11-03 23:30 UTC, coroa commented on pypsa/pf.py
>          return pd.Index([snapshots])
You should not drop the test for being list-like completely here! what if you get a list of snapshots?

https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.api.types.is_list_like.html should be a good way to go

2020-11-03 23:30 UTC, coroa commented on pypsa/components.py
> +from six import itervalues, iterkeys
you shouldn't need itervalues or iterkeys anymore, either.

2020-11-03 23:30 UTC, coroa commented on pypsa/io.py
> +from six import iteritems, iterkeys
Same

2020-11-03 23:30 UTC, coroa commented on pypsa/networkclustering.py
> +from six.moves import reduce
`reduce` lives in `functools` in python3

2020-11-03 23:30 UTC, coroa commented on pypsa/opf.py
> +from six import iteritems, itervalues
Idem

2020-11-03 23:30 UTC, coroa commented on test/test_pf_against_pandapower.py
>  )
You can get rid of the whole skipif, that was for not testing pandapower when running python2.

2020-11-03 23:30 UTC, coroa commented on pypsa/networkclustering.py
>  from six import itervalues, iteritems
Samesame

2021-04-27 06:30 UTC, merged