Add plotting example
PyPSA/PyPSA pull request #427
Opened 2022-08-01 15:14 UTC by energyLS

Closes #93.

## Changes proposed in this Pull Request
This PR adds a new example of the network plotting functionality to the docs based on a .ipynb.

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [ ] I consent to the release of this PR's code under the MIT license.

2022-08-01 18:57 UTC, fneum commented
This is still missing the notebook, is it? You might need to force-add the .ipynb as this file type is in .gitignore

2022-08-02 09:14 UTC, energyLS commented
> This is still missing the notebook, is it? You might need to force-add the .ipynb as this file type is in .gitignore
Thanks for the hint. Yes it was missing, since the notebook was not finished yet. Now it's added and ready for review.

2022-08-02 09:16 UTC, energyLS commented
@FabianHofmann agreed to review it, but I can't add him to the reviewers list lacking the permission to do so

2022-08-02 15:28 UTC, FabianHofmann requested changes

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "# n = pypsa.Network('/mnt/c/Users/scl38887/Documents/git/PyPSA/examples/notebooks/flow-plot.ipynb')\n",
```suggestion
```

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "Get mean generator power by bus and carrier"
```suggestion
    "Get mean generator power by bus and carrier:"
```

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "Plot the electricty flows"
```suggestion
    "Plot the electricity flows:"
```

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "Plot the electricity flows with different projection and geomap color"
```suggestion
    "Plot the electricity flows with a different projection and a colored map:"
```

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "Set arbitary values as flow argument using the MultiIndex of n.branches()"
```suggestion
    "Set arbitrary values as flow argument using the MultiIndex of `n.branches()`:"
```

2022-08-02 15:28 UTC, FabianHofmann commented on examples/notebooks/flow-plot.ipynb
> +    "Adjust link colors according to their mean load"
```suggestion
    "Adjust link colors according to their mean load:"
```

2022-08-03 11:49 UTC, energyLS commented
@FabianHofmann thanks for the review, all the suggestions are committed.

2022-08-03 13:14 UTC, FabianHofmann approved these changes

2022-08-03 13:15 UTC, merged