Fix HiGHS parsing for HiGHS v1.4.0
PyPSA/PyPSA pull request #501
Opened 2022-11-17 15:57 UTC by gailin-p

## Changes proposed in this Pull Request

### The problem 
I ran into an issue parsing solution files written by HiGHS using a new version of HiGHS (1.4.0, compiled from source code) and PyPSA 0.21.1. 
The issue seems to be the same as this one: https://groups.google.com/g/pypsa/c/15drmr_F1-Q/m/zh735MmTAQAJ 

### Proposed solution (this PR)

Update the parsing function to switch column headers for rows where the "Status" column output from HiGHS is empty, which was causing the remaining columns to be off by one from the header. 

### Open question 

Does PyPSA want to support different versions of HiGHS? If so, I can implement a version check so the new parsing is only performed on HiGHS v1.4.0+. I have not tested this on older versions of HiGHS, and I'm not sure when the breaking change was introduced to HiGHS (the [docs](https://ergo-code.github.io/HiGHS/man/guide.html) don't seem to include solution file syntax or release notes). 

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`. (not applicable)
- [ ] Unit tests for new features were added (if applicable). (not applicable) 
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable). (not applicable)
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

2022-11-18 09:18 UTC, fneum commented
I think it's fine to move the minimum requirements of HiGHS quickly as it's developing quickly. But mention in the release notes that 1.4.0 is the new minimum version.
@FabianHofmann might also affect `linopy`.

2022-11-18 12:51 UTC, fneum requested changes

2022-11-18 18:16 UTC, gailin-p commented
> I think it's fine to move the minimum requirements of HiGHS quickly as it's developing quickly. But mention in the release notes that 1.4.0 is the new minimum version.

I downgraded my local HiGHS version to 1.3 and confirmed that this code works there as well -- looks like the only change in 1.4 .sol files is that the "status" column is now sometimes empty. Updated the release notes accordingly.

2022-11-18 18:21 UTC, gailin-p commented on pypsa/linopt.py
> +    ].to_numpy()
resolved by [78c011c](https://github.com/PyPSA/PyPSA/pull/501/commits/78c011cd9b959d28ffa761ac2a2d4d0970020c2d)

2022-12-13 18:47 UTC, fneum approved these changes

2022-12-14 15:18 UTC, merged