Set up support section in docs
PyPSA/PyPSA pull request #612
Opened 2023-04-27 12:29 UTC by energyLS

## Changes proposed in this Pull Request
This PR revises the "contributions" section and adds the "support" section to include the link to stackoverflow and clarify the outreach channels.
Apart from the docs, it adds stackoverflow to the github issue template and readme.

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [ ] I consent to the release of this PR's code under the MIT license.

2023-04-27 12:44 UTC, energyLS commented
@euronion I'd be happy to receive your review, can't add you though due to limited rights.

2023-04-27 15:34 UTC, energyLS commented
@euronion I have chatted with @fneum who is in general fine with the proposed structure (didn't look into detail though). We have now added [shields](https://img.shields.io/stackexchange/stackoverflow/t/pypsa) to readme and docs.

2023-04-28 13:51 UTC, euronion requested changes
* Looking mostly good, thank you!

* Shields are always nice ;-)

* I think we can get rid of the "Contributing" section in the documentation then?

2023-04-28 13:51 UTC, euronion commented on README.md
> +use the [discord server](https://discord.gg/JTdvaEBb).
```suggestion
-   To **discuss** with other PyPSA users, organise projects, share news, and get in touch with the community you can use the [discord server](https://discord.gg/JTdvaEBb).
```

2023-04-28 13:51 UTC, euronion commented on doc/support.rst
> +use the `discord server <https://discord.gg/JTdvaEBb>`_.
```suggestion
* To **discuss** with other PyPSA users, organise projects, share news, and get in touch with the community you can use the [discord server](https://discord.gg/JTdvaEBb).
```

2023-04-28 13:51 UTC, euronion commented on doc/support.rst
> +* For **contributions**, visit PyPSA on `Github <https://github.com/PyPSA/PyPSA>`_.
```suggestion
* We strongly welcome anyone interested in providing **contributions** to this project. If you have any ideas, suggestions or encounter problems, feel invited to file issues or make pull requests on `Github <https://github.com/PyPSA/PyPSA>`_.
```

Consistency with README.md

2023-04-30 08:39 UTC, fneum approved these changes
Thanks for taking care of this!

2023-04-30 08:39 UTC, merged