Feature/snapshot weights
PyPSA/PyPSA pull request #641
Opened 2023-05-24 08:18 UTC by martinhjel

As discussed in #639 

## Changes proposed in this Pull Request
- Add flag to compute snapshot_weightings with timedelta if snapshots are of type pd.DatetimeIndex. Default is False.
- Add argument for selecting snapshot weightings, set default to 1.0.
- Add pandapower and scikit-learn to environment.yaml. Limit pandas version as pandapower fails for version >=2.0 of pandas due to .iteritems(). 
- Add type hints.
- Add pyproject.toml file for project configurations to align with [PEP 518](https://peps.python.org/pep-0518/) (should perhaps have been added in a separate PR..)

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

2023-05-24 09:10 UTC, FabianHofmann commented
Hey @martinhjel! Thanks for your contribution! 

The PR looks nice  :) But it is mixing topics a bit. I am wondering about the pandas limitation. The pandapower repo also uses pandas >= 2.0 in there CI (see https://github.com/e2nIEE/pandapower/actions/runs/5043342658/jobs/9045012640#step:4:53). Did you update to their latest package?

2023-05-24 09:49 UTC, martinhjel commented
Found out I had pandapower 2.8.0 installed, updated to 2.13, and the `AttributeError: 'Series' object has no attribute 'iteritems'` disappeared. Removed the dependency now.

2023-05-24 11:15 UTC, FabianHofmann requested changes
Just some points regarding the docs

2023-05-24 11:15 UTC, FabianHofmann commented on doc/release_notes.rst
> +  that can be used to change the default snapshot weightings, and ``weightings_from_timedelta``
```suggestion
  to change the default snapshot weightings, and ``weightings_from_timedelta``
```

2023-05-24 11:15 UTC, FabianHofmann commented on pypsa/components.py
> +            Use the timedelta of `snapshots` as `snapshot_weightings` if `snapshots` is of type `pd.DatetimeIndex`.  Defaults to False.
```suggestion
            Wheter to use the timedelta of `snapshots` as `snapshot_weightings` if `snapshots` is of type `pd.DatetimeIndex`.  Defaults to False.
```

2023-06-01 08:26 UTC, martinhjel commented
@FabianHofmann, is there anything else I have to do to complete this PR?

2023-06-01 08:33 UTC, FabianHofmann approved these changes

2023-06-01 09:54 UTC, merged